version: '3'

services:
  database:
    build:
      context: ./database
    container_name: database
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:3000"
    depends_on:
      - database
    env_file:
      - .env

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
